# Generated by Django 5.0.2 on 2025-06-15 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Місто")),
                ("country", models.CharField(max_length=100, verbose_name="Країна")),
                ("temperature", models.FloatField(verbose_name="Температура")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Опис погоди"),
                ),
                (
                    "searched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата пошуку"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Історія пошуку",
                "verbose_name_plural": "Історія пошуків",
                "ordering": ["-searched_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Місто")),
                ("country", models.CharField(max_length=100, verbose_name="Країна")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата додавання"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Улюблене місце",
                "verbose_name_plural": "Улюблені місця",
                "unique_together": {("user", "city", "country")},
            },
        ),
    ]
